# Generated by Django 6.0.7 on 2026-07-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('loading', 'Loading'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('loading', 'Loading'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
