# Generated by Django 6.0.7 on 2026-07-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('busy', 'Busy')], default='available', max_length=20)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='accounts.driver')),
            ],
        ),
    ]
